spring:
  application:
    name: dev-manager
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a120310
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
  aop:
    proxy-target-class: true
    auto: true

jpa:  #JPA配置
  show-sql: true
  hibernate:
  ddl-auto: update # 第一次建表create  后面用update

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zingw.demo.pojo  # 注意：对应实体类的路径

mapper:
  mappers:
  - com.zingw.demo.utils.MyMapper
  not-empty: false
  identity: MYSQL


